name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 */2 * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: General
        uses: nyable/metrics@master
        with:
          filename: images/metrics.general.svg
          token: ${{ secrets.METRICS_TOKEN }}
      - name: Full-year calendar
        uses: nyable/metrics@master
        with:
          filename: images/metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - name: Recently starred
        uses: nyable/metrics@master
        with:
          filename: images/metrics.plugin.stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 3
